# 站点信息
site_name: Genesis Deep Learning Framework
site_description: 'A lightweight deep learning framework built from scratch in Python'
site_author: 'Genesis Team'
site_url: 'https://phonism.github.io/genesis'

# 仓库信息
repo_name: 'phonism/genesis'
repo_url: 'https://github.com/phonism/genesis'
edit_uri: 'edit/main/docs/'

# 版权信息
copyright: 'Copyright &copy; 2025 Genesis Team'

# 主题配置
theme:
  name: material
  language: zh
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github

# 插件配置
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
  - section-index

# Markdown扩展
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: phonism
      repo: genesis
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# 额外配置
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/phonism/genesis
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/genesis/

# MathJax配置
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

# 导航结构
nav:
  - 首页: index.md
  - 快速开始:
    - getting-started/index.md
    - 安装: getting-started/installation.md
    - 第一个程序: getting-started/first-steps.md
  - 架构设计:
    - architecture/index.md
    - 设计理念: architecture/design-principles.md
    - 张量系统: architecture/tensor-system.md
    - 后端抽象: architecture/backend-abstraction.md
  - 核心组件:
    - core-components/index.md
    - 自动微分: core-components/autograd.md
    - 张量操作: core-components/tensor.md
    - 函数式接口: core-components/functional.md
    - 数据类型: core-components/dtypes.md
  - NDArray系统:
    - ndarray/index.md
    - CPU后端: ndarray/cpu-backend.md
    - CUDA后端: ndarray/cuda-backend.md
    - 内存管理: ndarray/memory-management.md
  - 神经网络:
    - neural-networks/index.md
    - 基础模块: neural-networks/modules.md
    - 注意力机制: neural-networks/attention.md
    - 层归一化: neural-networks/layer-norm.md
    - Triton优化: neural-networks/triton-optimization.md
    - 分布式训练: neural-networks/distributed.md
  - 训练系统:
    - training/index.md
    - 优化器: training/optimizers.md
    - 学习率调度: training/lr-schedulers.md
    - 混合精度: training/mixed-precision.md
    - 模型保存: training/checkpointing.md
  - 模型库:
    - models/index.md
    - Qwen实现: models/qwen.md
  - 教程:
    - tutorials/index.md
    - 基础训练: tutorials/basic-training.md
    - 自定义算子: tutorials/custom-ops.md
    - 性能调优: tutorials/performance-tuning.md
  - 性能优化:
    - performance/optimization-guide.md
  - API参考:
    - api-reference/index.md
    - genesis: api-reference/genesis.md
    - nn: api-reference/nn.md
    - optim: api-reference/optim.md
    - utils: api-reference/utils.md
  - 贡献指南:
    - contributing/index.md
    - 开发环境: contributing/development.md
    - 测试规范: contributing/testing.md